version: "3.7"

services:

    mongo:
        image: mongo:4.2.5
        restart: always
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express:0.54.0
        restart: always
        ports:
            - 8081:8081

    ngrok:
        image: wernight/ngrok
        ports: 
            - 4040:4040
        command: ngrok http server:8080

    server:
        build: ./server
        ports:
            - 8080:8080
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
