version: "3.7"

services:

    mongo:
        image: mongo:4.2.5
        restart: always
        ports:
            - 27017:27017
        # env_file:
            #   - ./mongo/mongo-credentials.env
        # volumes:
            #   - ./mongo/conf:/etc/mongos
            # command: --config /etc/mongo/mongod.conf

    mongo-express:
        image: mongo-express:0.54.0
        restart: always
        ports:
            - 8081:8081
        # env_file:
            #   - ./mongo/mongo-credentials.env

    server:
        image: node:12.16.2
        ports:
            - 8080:8080
            - 9229:9229
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
        working_dir: /usr/src/server
        volumes:
            - ./server:/usr/src/server
        stdin_open: true
        tty: true
        command: /bin/bash
