export const SAVE_CURRENT_REQUEST = "SAVE_CURRENT_REQUEST";
export const SAVE_CALL_NOTES = "SAVE_CALL_NOTES";
export const SAVE_WELFARE_FREQUENCY = "SAVE_WELFARE_FREQUENCY";
export const RESET_PATIENT_DATA = "RESET_PATIENT_DATA";
